/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.springboot;

import static org.junit.Assert.*;

import org.junit.Test;

public class ServerMainTest {
    @Test
    public void testAppHasAGreeting() {
        ServerMain classUnderTest = new ServerMain();
        assertNotNull("test", classUnderTest);
    }
}
